
services:
  postgres_db:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: postgres_db_RAG
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatbotdb_2025
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docuBot111
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: "exit 0"

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container  
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db

volumes:
  postgres_db_data:
  pgadmin_data: